package ziyue.tjmetro.mod;

import net.minecraft.world.level.block.Blocks;
import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.ChatFormatting;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.util.Mth;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.Property;
import net.minecraft.world.level.block.state.properties.BooleanProperty;
import net.minecraft.world.level.block.state.properties.IntegerProperty;
import net.minecraft.world.level.block.state.properties.EnumProperty;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.shapes.VoxelShape;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.MinecraftServer;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.LightTexture;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.culling.Frustum;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.components.AbstractWidget;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.blaze3d.platform.NativeImage;
import com.mojang.math.Axis;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.level.block.SlabBlock;
import org.mtr.registry.ObjectHolder;
import org.mtr.block.BlockCeiling;
import org.mtr.block.BlockPlatform;
import org.mtr.block.BlockPlatformSlab;
import org.mtr.block.BlockTicketBarrier;
import org.mtr.item.ItemBlockEnchanted;
import ziyue.tjmetro.mod.block.*;
import ziyue.tjmetro.mod.block.base.StairBlock;

/**
 * @since 1.0.0-beta-1
 */

public interface BlockList
{
    BlockRegistryObject LOGO = Registry.registerBlockWithBlockItem("logo", () -> (new BlockLogo()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLAYER_DETECTOR = Registry.registerBlockWithBlockItem("player_detector", () -> (new BlockPlayerDetector()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject ROLLING = Registry.registerBlockWithBlockItem("rolling", () -> (new BlockRolling()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CEILING_NOT_LIT = Registry.registerBlockWithBlockItem("ceiling_not_lit", () -> (new BlockCeiling(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_COLOR_CEILING = Registry.registerBlockWithBlockItem("station_color_ceiling", () -> (new BlockStationColorCeilingAuto()), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_COLOR_CEILING_LIGHT = Registry.registerBlockWithBlockItem("station_color_ceiling_light", () -> (new BlockStationColorCeiling(15)), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_COLOR_CEILING_NO_LIGHT = Registry.registerBlockWithBlockItem("station_color_ceiling_no_light", () -> (new BlockStationColorCeiling(0)), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_COLOR_CEILING_NOT_LIT = Registry.registerBlockWithBlockItem("station_color_ceiling_not_lit", () -> (new BlockStationColorCeiling(0)), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_SIGN_1 = Registry.registerBlockWithBlockItem("station_name_sign_1", () -> (new BlockStationNameSign1()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_SIGN_2 = Registry.registerBlockWithBlockItem("station_name_sign_2", () -> (new BlockStationNameSign2()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject APG_CORNER = Registry.registerBlockWithBlockItem("apg_corner", () -> (new BlockAPGCorner()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_1 = Registry.registerBlockWithBlockItem("platform_tj_1", () -> (new BlockPlatform(BlockBehaviour.Properties.of(), false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_1_INDENTED = Registry.registerBlockWithBlockItem("platform_tj_1_indented", () -> (new BlockPlatform(BlockBehaviour.Properties.of(), true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_1_SLAB = Registry.registerBlockWithBlockItem("platform_tj_1_slab", () -> (new BlockPlatformSlab(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_2 = Registry.registerBlockWithBlockItem("platform_tj_2", () -> (new BlockPlatform(BlockBehaviour.Properties.of(), false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_2_INDENTED = Registry.registerBlockWithBlockItem("platform_tj_2_indented", () -> (new BlockPlatform(BlockBehaviour.Properties.of(), true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_2_SLAB = Registry.registerBlockWithBlockItem("platform_tj_2_slab", () -> (new BlockPlatformSlab(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject MARBLE_GRAY = Registry.registerBlockWithBlockItem("marble_gray", () -> (new Block(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject MARBLE_GRAY_SLAB = Registry.registerBlockWithBlockItem("marble_gray_slab", () -> (new SlabBlock(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject MARBLE_GRAY_STAIRS = Registry.registerBlockWithBlockItem("marble_gray_stairs", () -> (new StairBlock(net.minecraft.world.level.block.Blocks.BRICKS)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject MARBLE_YELLOW = Registry.registerBlockWithBlockItem("marble_yellow", () -> (new Block(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject MARBLE_YELLOW_SLAB = Registry.registerBlockWithBlockItem("marble_yellow_slab", () -> (new SlabBlock(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject MARBLE_YELLOW_STAIRS = Registry.registerBlockWithBlockItem("marble_yellow_stairs", () -> (new StairBlock(net.minecraft.world.level.block.Blocks.BRICKS)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject TIME_DISPLAY = Registry.registerBlockWithBlockItem("time_display", () -> (new BlockTimeDisplay()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject EMERGENCY_EXIT_SIGN = Registry.registerBlockWithBlockItem("emergency_exit_sign", () -> (new BlockEmergencyExitSign()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject SERVICE_CORRIDOR_SIGN = Registry.registerBlockWithBlockItem("service_corridor_sign", () -> (new BlockServiceCorridorSign()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject ROADBLOCK = Registry.registerBlockWithBlockItem("roadblock", () -> (new BlockRoadblock()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject ROADBLOCK_SIGN = Registry.registerBlockWithBlockItem("roadblock_sign", () -> (new BlockRoadblockSign()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject BENCH = Registry.registerBlockWithBlockItem("bench", () -> (new BlockBench()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CUSTOM_COLOR_CONCRETE = Registry.registerBlockWithBlockItem("custom_color_concrete", () -> (new BlockCustomColorConcrete()), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CUSTOM_COLOR_CONCRETE_SLAB = Registry.registerBlockWithBlockItem("custom_color_concrete_slab", () -> (new BlockCustomColorConcreteSlab()), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CUSTOM_COLOR_CONCRETE_STAIRS = Registry.registerBlockWithBlockItem("custom_color_concrete_stairs", () -> (new BlockCustomColorConcreteStairs()), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_4 = Registry.registerBlockWithBlockItem("railway_sign_wall_4", () -> (new BlockRailwaySignWall(4)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_6 = Registry.registerBlockWithBlockItem("railway_sign_wall_6", () -> (new BlockRailwaySignWall(6)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_8 = Registry.registerBlockWithBlockItem("railway_sign_wall_8", () -> (new BlockRailwaySignWall(8)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_10 = Registry.registerBlockWithBlockItem("railway_sign_wall_10", () -> (new BlockRailwaySignWall(10)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_MIDDLE = Registry.registerBlock("railway_sign_wall_middle", () -> (new BlockRailwaySignWall(0)));
    BlockRegistryObject RAILWAY_SIGN_WALL_DOUBLE_4 = Registry.registerBlockWithBlockItem("railway_sign_wall_double_4", () -> (new BlockRailwaySignWallDouble(4)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_DOUBLE_6 = Registry.registerBlockWithBlockItem("railway_sign_wall_double_6", () -> (new BlockRailwaySignWallDouble(6)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_DOUBLE_8 = Registry.registerBlockWithBlockItem("railway_sign_wall_double_8", () -> (new BlockRailwaySignWallDouble(8)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_DOUBLE_10 = Registry.registerBlockWithBlockItem("railway_sign_wall_double_10", () -> (new BlockRailwaySignWallDouble(10)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_DOUBLE_MIDDLE = Registry.registerBlock("railway_sign_wall_double_middle", () -> (new BlockRailwaySignWallDouble(0)));
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_2 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_2", () -> (new BlockRailwaySignWallBig(2)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_3 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_3", () -> (new BlockRailwaySignWallBig(3)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_4 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_4", () -> (new BlockRailwaySignWallBig(4)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_5 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_5", () -> (new BlockRailwaySignWallBig(5)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_6 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_6", () -> (new BlockRailwaySignWallBig(6)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_7 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_7", () -> (new BlockRailwaySignWallBig(7)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_8 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_8", () -> (new BlockRailwaySignWallBig(8)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_9 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_9", () -> (new BlockRailwaySignWallBig(9)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_10 = Registry.registerBlockWithBlockItem("railway_sign_wall_big_10", () -> (new BlockRailwaySignWallBig(10)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_WALL_BIG_MIDDLE = Registry.registerBlock("railway_sign_wall_big_middle", () -> (new BlockRailwaySignWallBig(0)));
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_3_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_3_odd", () -> (new BlockRailwaySignTianjin(3, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_4_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_4_odd", () -> (new BlockRailwaySignTianjin(4, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_5_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_5_odd", () -> (new BlockRailwaySignTianjin(5, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_6_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_6_odd", () -> (new BlockRailwaySignTianjin(6, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_7_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_7_odd", () -> (new BlockRailwaySignTianjin(7, true)), CreativeModeTabs.TIANJIN_METRO);
    //    BlockRegistryObject RAILWAY_SIGN_TIANJIN_8_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_8_odd", () -> (new BlockRailwaySignTianjin(8, true)), CreativeModeTabs.TIANJIN_METRO);
//    BlockRegistryObject RAILWAY_SIGN_TIANJIN_9_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_9_odd", () -> (new BlockRailwaySignTianjin(9, true)), CreativeModeTabs.TIANJIN_METRO);
//    BlockRegistryObject RAILWAY_SIGN_TIANJIN_10_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_10_odd", () -> (new BlockRailwaySignTianjin(10, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_2_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_2_even", () -> (new BlockRailwaySignTianjin(2, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_3_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_3_even", () -> (new BlockRailwaySignTianjin(3, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_4_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_4_even", () -> (new BlockRailwaySignTianjin(4, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_5_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_5_even", () -> (new BlockRailwaySignTianjin(5, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_6_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_6_even", () -> (new BlockRailwaySignTianjin(6, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_7_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_7_even", () -> (new BlockRailwaySignTianjin(7, false)), CreativeModeTabs.TIANJIN_METRO);
    //    BlockRegistryObject RAILWAY_SIGN_TIANJIN_8_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_8_even", () -> (new BlockRailwaySignTianjin(8, false)), CreativeModeTabs.TIANJIN_METRO);
//    BlockRegistryObject RAILWAY_SIGN_TIANJIN_9_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_9_even", () -> (new BlockRailwaySignTianjin(9, false)), CreativeModeTabs.TIANJIN_METRO);
//    BlockRegistryObject RAILWAY_SIGN_TIANJIN_10_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_10_even", () -> (new BlockRailwaySignTianjin(10, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_MIDDLE = Registry.registerBlock("railway_sign_tianjin_middle", () -> (new BlockRailwaySignTianjin(0, false)));
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_POLE = Registry.registerBlockWithBlockItem("railway_sign_tianjin_pole", () -> (new BlockRailwaySignTianjinPole()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_ENTRANCE_TIANJIN = Registry.registerBlockWithBlockItem("station_name_entrance_tianjin", () -> (new BlockStationNameEntranceTianjin(false, BlockStationNameEntranceTianjin.Type.TRT)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_ENTRANCE_TIANJIN_PINYIN = Registry.registerBlockWithBlockItem("station_name_entrance_tianjin_pinyin", () -> (new BlockStationNameEntranceTianjin(true, BlockStationNameEntranceTianjin.Type.TRT)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_ENTRANCE_TIANJIN_BMT = Registry.registerBlockWithBlockItem("station_name_entrance_tianjin_bmt", () -> (new BlockStationNameEntranceTianjin(false, BlockStationNameEntranceTianjin.Type.BMT)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_ENTRANCE_TIANJIN_BMT_PINYIN = Registry.registerBlockWithBlockItem("station_name_entrance_tianjin_bmt_pinyin", () -> (new BlockStationNameEntranceTianjin(true, BlockStationNameEntranceTianjin.Type.BMT)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_ENTRANCE_TIANJIN_JINJING = Registry.registerBlockWithBlockItem("station_name_entrance_tianjin_jinjing", () -> (new BlockStationNameEntranceTianjin(false, BlockStationNameEntranceTianjin.Type.JINJING)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_ENTRANCE_TIANJIN_JINJING_PINYIN = Registry.registerBlockWithBlockItem("station_name_entrance_tianjin_jinjing_pinyin", () -> (new BlockStationNameEntranceTianjin(true, BlockStationNameEntranceTianjin.Type.JINJING)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PSD_DOOR_TIANJIN_BLOCK = Registry.registerBlock("psd_door_tianjin", () -> (new BlockPSDDoorTianjin()));
    BlockRegistryObject PSD_GLASS_TIANJIN_BLOCK = Registry.registerBlock("psd_glass_tianjin", () -> (new BlockPSDGlassTianjin()));
    BlockRegistryObject PSD_GLASS_END_TIANJIN_BLOCK = Registry.registerBlock("psd_glass_end_tianjin", () -> (new BlockPSDGlassEndTianjin()));
    BlockRegistryObject PSD_TOP_TIANJIN = Registry.registerBlock("psd_top_tianjin", () -> (new BlockPSDTopTianjin(false)));
    BlockRegistryObject METAL_DETECTION_DOOR = Registry.registerBlockWithBlockItem("metal_detection_door", () -> (new BlockMetalDetectionDoor()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject HIGH_SPEED_REPEATER = Registry.registerBlockWithBlockItem("high_speed_repeater", () -> (new BlockHighSpeedRepeater()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_WALL_LEGACY = Registry.registerBlockWithBlockItem("station_name_wall_legacy", () -> (new BlockStationNameWallLegacy()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_PLATE = Registry.registerBlockWithBlockItem("station_name_plate", () -> (new BlockStationNamePlate()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_PLATE_MIDDLE = Registry.registerBlock("station_name_plate_middle", () -> (new BlockStationNamePlate()));
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_2_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_2_odd", () -> (new BlockRailwaySignTianjinBMT(2, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_3_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_3_odd", () -> (new BlockRailwaySignTianjinBMT(3, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_4_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_4_odd", () -> (new BlockRailwaySignTianjinBMT(4, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_5_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_5_odd", () -> (new BlockRailwaySignTianjinBMT(5, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_6_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_6_odd", () -> (new BlockRailwaySignTianjinBMT(6, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_7_ODD = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_7_odd", () -> (new BlockRailwaySignTianjinBMT(7, true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_2_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_2_even", () -> (new BlockRailwaySignTianjinBMT(2, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_3_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_3_even", () -> (new BlockRailwaySignTianjinBMT(3, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_4_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_4_even", () -> (new BlockRailwaySignTianjinBMT(4, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_5_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_5_even", () -> (new BlockRailwaySignTianjinBMT(5, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_6_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_6_even", () -> (new BlockRailwaySignTianjinBMT(6, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_7_EVEN = Registry.registerBlockWithBlockItem("railway_sign_tianjin_bmt_7_even", () -> (new BlockRailwaySignTianjinBMT(7, false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject RAILWAY_SIGN_TIANJIN_BMT_MIDDLE = Registry.registerBlock("railway_sign_tianjin_bmt_middle", () -> (new BlockRailwaySignTianjinBMT(0, false)));
    BlockRegistryObject APG_DOOR_TIANJIN_BLOCK = Registry.registerBlock("apg_door_tianjin", () -> (new BlockAPGDoorTianjin()));
    BlockRegistryObject APG_GLASS_TIANJIN_BLOCK = Registry.registerBlock("apg_glass_tianjin", () -> (new BlockAPGGlassTianjin()));
    BlockRegistryObject APG_GLASS_END_TIANJIN_BLOCK = Registry.registerBlock("apg_glass_end_tianjin", () -> (new BlockAPGGlassEndTianjin()));
    BlockRegistryObject APG_DOOR_TIANJIN_BMT_BLOCK = Registry.registerBlock("apg_door_tianjin_bmt", () -> (new BlockAPGDoorTianjinBMT()));
    BlockRegistryObject APG_GLASS_TIANJIN_BMT_BLOCK = Registry.registerBlock("apg_glass_tianjin_bmt", () -> (new BlockAPGGlassTianjinBMT()));
    BlockRegistryObject APG_GLASS_END_TIANJIN_BMT_BLOCK = Registry.registerBlock("apg_glass_end_tianjin_bmt", () -> (new BlockAPGGlassEndTianjinBMT()));
    BlockRegistryObject METAL_POLE_BMT = Registry.registerBlockWithBlockItem("metal_pole_bmt", () -> (new BlockMetalPoleBMT()), BlockItem::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PSD_DOOR_TIANJIN_BMT_BLOCK = Registry.registerBlock("psd_door_tianjin_bmt", () -> (new BlockPSDDoorTianjinBMT()));
    BlockRegistryObject PSD_GLASS_TIANJIN_BMT_BLOCK = Registry.registerBlock("psd_glass_tianjin_bmt", () -> (new BlockPSDGlassTianjinBMT()));
    BlockRegistryObject PSD_GLASS_END_TIANJIN_BMT_BLOCK = Registry.registerBlock("psd_glass_end_tianjin_bmt", () -> (new BlockPSDGlassEndTianjinBMT()));
    BlockRegistryObject PSD_TOP_TIANJIN_BMT = Registry.registerBlock("psd_top_tianjin_bmt", () -> (new BlockPSDTopTianjinBMT()));
    BlockRegistryObject APG_DOOR_TIANJIN_TRT_BLOCK = Registry.registerBlock("apg_door_tianjin_trt", () -> (new BlockAPGDoorTianjinTRT()));
    BlockRegistryObject APG_GLASS_TIANJIN_TRT_BLOCK = Registry.registerBlock("apg_glass_tianjin_trt", () -> (new BlockAPGGlassTianjinTRT()));
    BlockRegistryObject APG_GLASS_END_TIANJIN_TRT_BLOCK = Registry.registerBlock("apg_glass_end_tianjin_trt", () -> (new BlockAPGGlassEndTianjinTRT()));
    BlockRegistryObject PLATFORM_TJ_LINE_11_1 = Registry.registerBlockWithBlockItem("platform_tj_line_11_1", () -> (new BlockPlatform(BlockBehaviour.Properties.of(), false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_LINE_11_1_INDENTED = Registry.registerBlockWithBlockItem("platform_tj_line_11_1_indented", () -> (new BlockPlatform(BlockBehaviour.Properties.of(), true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_LINE_11_1_SLAB = Registry.registerBlockWithBlockItem("platform_tj_line_11_1_slab", () -> (new BlockPlatformSlab(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_LINE_11_2 = Registry.registerBlockWithBlockItem("platform_tj_line_11_2", () -> (new BlockPlatform(BlockBehaviour.Properties.of(), false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_LINE_11_2_INDENTED = Registry.registerBlockWithBlockItem("platform_tj_line_11_2_indented", () -> (new BlockPlatform(BlockBehaviour.Properties.of(), true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PLATFORM_TJ_LINE_11_2_SLAB = Registry.registerBlockWithBlockItem("platform_tj_line_11_2_slab", () -> (new BlockPlatformSlab(BlockBehaviour.Properties.of())), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject SECURITY_CHECK_SIGN = Registry.registerBlockWithBlockItem("security_check_sign", () -> (new BlockSecurityCheckSign()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAVIGATOR_POLE = Registry.registerBlockWithBlockItem("station_navigator_pole", () -> (new BlockStationNavigatorPole()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAVIGATOR_3 = Registry.registerBlockWithBlockItem("station_navigator_3", () -> (new BlockStationNavigator(3)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAVIGATOR_4 = Registry.registerBlockWithBlockItem("station_navigator_4", () -> (new BlockStationNavigator(4)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAVIGATOR_5 = Registry.registerBlockWithBlockItem("station_navigator_5", () -> (new BlockStationNavigator(5)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAVIGATOR_MIDDLE = Registry.registerBlock("station_navigator_middle", () -> (new BlockStationNavigator(0)));
    BlockRegistryObject STATION_NAME_PROJECTOR = Registry.registerBlockWithBlockItem("station_name_projector", () -> (new BlockStationNameProjector()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PSD_DOOR_TIANJIN_JINJING_BLOCK = Registry.registerBlock("psd_door_tianjin_jinjing", () -> (new BlockPSDDoorTianjinJinjing()));
    BlockRegistryObject PSD_GLASS_TIANJIN_JINJING_BLOCK = Registry.registerBlock("psd_glass_tianjin_jinjing", () -> (new BlockPSDGlassTianjinJinjing()));
    BlockRegistryObject PSD_GLASS_END_TIANJIN_JINJING_BLOCK = Registry.registerBlock("psd_glass_end_tianjin_jinjing", () -> (new BlockPSDGlassEndTianjinJinjing()));
    BlockRegistryObject PSD_TOP_TIANJIN_JINJING = Registry.registerBlock("psd_top_tianjin_jinjing", () -> (new BlockPSDTopTianjin(true)));
    BlockRegistryObject TIME_DISPLAY_EVEN = Registry.registerBlockWithBlockItem("time_display_even", () -> (new BlockTimeDisplayEven()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject NO_ENTERING_SIGN = Registry.registerBlockWithBlockItem("no_entering_sign", () -> (new BlockNoEnteringSign()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CEILING_TIANJIN = Registry.registerBlockWithBlockItem("ceiling_tianjin", () -> (new BlockCeilingTianjinAuto()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CEILING_TIANJIN_LIGHT = Registry.registerBlockWithBlockItem("ceiling_tianjin_light", () -> (new BlockCeilingTianjin(15)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CEILING_TIANJIN_NO_LIGHT = Registry.registerBlockWithBlockItem("ceiling_tianjin_no_light", () -> (new BlockCeilingTianjin(0)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CEILING_TIANJIN_NOT_LIT = Registry.registerBlockWithBlockItem("ceiling_tianjin_not_lit", () -> (new BlockCeilingTianjin(0)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject TICKET_BARRIER_TIANJIN_ENTRANCE = Registry.registerBlockWithBlockItem("ticket_barrier_tianjin_entrance", () -> (new BlockTicketBarrier(BlockBehaviour.Properties.of(), true)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject TICKET_BARRIER_TIANJIN_EXIT = Registry.registerBlockWithBlockItem("ticket_barrier_tianjin_exit", () -> (new BlockTicketBarrier(BlockBehaviour.Properties.of(), false)), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject APG_DOOR_TIANJIN_JINJING_BLOCK = Registry.registerBlock("apg_door_tianjin_jinjing", () -> (new BlockAPGDoorTianjinJinjing()));
    BlockRegistryObject APG_GLASS_TIANJIN_JINJING_BLOCK = Registry.registerBlock("apg_glass_tianjin_jinjing", () -> (new BlockAPGGlassTianjinJinjing()));
    BlockRegistryObject APG_GLASS_END_TIANJIN_JINJING_BLOCK = Registry.registerBlock("apg_glass_end_tianjin_jinjing", () -> (new BlockAPGGlassEndTianjinJinjing()));
    BlockRegistryObject STATION_SIGN = Registry.registerBlockWithBlockItem("station_sign", () -> (new BlockStationSign()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject ROUTE_MAP_BMT = Registry.registerBlockWithBlockItem("route_map_bmt", () -> (new BlockRouteMapBMT()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject ROUTE_MAP_BMT_MIDDLE = Registry.registerBlock("route_map_bmt_middle", () -> (new BlockRouteMapBMT()));
    BlockRegistryObject STATION_SIGN_BMT = Registry.registerBlockWithBlockItem("station_sign_bmt", () -> (new BlockStationSignBMT()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject TRASH_CAN = Registry.registerBlockWithBlockItem("trash_can", () -> (new BlockTrashCan()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject STATION_NAME_SIGN_TIANJIN = Registry.registerBlockWithBlockItem("station_name_sign_tianjin", () -> (new BlockStationNameSignTianjin()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PIDS_TIANJIN = Registry.registerBlockWithBlockItem("pids_tianjin", () -> (new BlockPIDSTianjin()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject SMOKE_ALARM = Registry.registerBlockWithBlockItem("smoke_alarm", () -> (new BlockSmokeAlarm()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CUSTOM_COLOR_MOSAIC_TILE = Registry.registerBlockWithBlockItem("custom_color_mosaic_tile", () -> (new BlockCustomColorMosaicTile()), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CUSTOM_COLOR_MOSAIC_TILE_SLAB = Registry.registerBlockWithBlockItem("custom_color_mosaic_tile_slab", () -> (new BlockCustomColorMosaicTileSlab()), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject CUSTOM_COLOR_MOSAIC_TILE_STAIRS = Registry.registerBlockWithBlockItem("custom_color_mosaic_tile_stairs", () -> (new BlockCustomColorMosaicTileStairs()), ItemBlockEnchanted::new, CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject PIDS_TIANJIN_SINGLE = Registry.registerBlockWithBlockItem("pids_tianjin_single", () -> (new BlockPIDSTianjinSingle()), CreativeModeTabs.TIANJIN_METRO);
    BlockRegistryObject APG_DOOR_SINGLE_LEFT = Registry.registerBlock("apg_door_single_left", () -> (new BlockAPGDoorSingle(true)));
    BlockRegistryObject APG_DOOR_SINGLE_RIGHT = Registry.registerBlock("apg_door_single_right", () -> (new BlockAPGDoorSingle(false)));
    BlockRegistryObject PSD_DOOR_SINGLE_LEFT = Registry.registerBlock("psd_door_single_left", () -> (new BlockPSDDoorSingle(true)));
    BlockRegistryObject PSD_DOOR_SINGLE_RIGHT = Registry.registerBlock("psd_door_single_right", () -> (new BlockPSDDoorSingle(false)));

    static void registerBlocks() {
        // Calling this class to initialize constants
        TianjinMetro.LOGGER.info("Registering blocks");
    }
}
