package ziyue.tjmetro.mod;

import net.minecraft.core.BlockPos;
import net.minecraft.core.Direction;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.ChatFormatting;
import net.minecraft.util.FormattedCharSequence;
import net.minecraft.util.Mth;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.InteractionResult;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.level.ItemLike;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.BlockGetter;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.block.state.StateDefinition;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.Property;
import net.minecraft.world.level.block.state.properties.BooleanProperty;
import net.minecraft.world.level.block.state.properties.IntegerProperty;
import net.minecraft.world.level.block.state.properties.EnumProperty;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.shapes.VoxelShape;
import net.minecraft.world.phys.shapes.Shapes;
import net.minecraft.world.phys.shapes.CollisionContext;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.MinecraftServer;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.LightTexture;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.culling.Frustum;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.EditBox;
import net.minecraft.client.gui.components.AbstractWidget;
import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import com.mojang.blaze3d.platform.NativeImage;
import com.mojang.math.Axis;
import net.minecraft.client.renderer.RenderType;
import ziyue.tjmetro.mod.block.BlockSmokeAlarm;
import ziyue.tjmetro.mod.config.ConfigClient;
import ziyue.tjmetro.mod.render.*;
import ziyue.tjmetro.mod.sound.LoopingSoundInstance;

/**
 * @since 1.0.0-beta-1
 */

public final class TianjinMetroClient
{
    public static final LoopingSoundInstance SMOKE_ALARM_SOUND_INSTANCE = new LoopingSoundInstance("smoke_alarm");

    public static void init() {
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.LOGO);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.STATION_NAME_SIGN_1);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.STATION_NAME_SIGN_2);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_CORNER);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_1);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_1_INDENTED);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_1_SLAB);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_2);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_2_INDENTED);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_2_SLAB);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.EMERGENCY_EXIT_SIGN);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.SERVICE_CORRIDOR_SIGN);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_DOOR_TIANJIN_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_GLASS_TIANJIN_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_GLASS_END_TIANJIN_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_DOOR_TIANJIN_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_GLASS_TIANJIN_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_GLASS_END_TIANJIN_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_DOOR_TIANJIN_BMT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_GLASS_TIANJIN_BMT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_GLASS_END_TIANJIN_BMT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.translucent(), BlockList.ROLLING);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_DOOR_TIANJIN_BMT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_GLASS_TIANJIN_BMT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_GLASS_END_TIANJIN_BMT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_DOOR_TIANJIN_TRT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_GLASS_TIANJIN_TRT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_GLASS_END_TIANJIN_TRT_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.HIGH_SPEED_REPEATER);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_LINE_11_1);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_LINE_11_1_INDENTED);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_LINE_11_1_SLAB);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_LINE_11_2);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_LINE_11_2_INDENTED);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PLATFORM_TJ_LINE_11_2_SLAB);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.SECURITY_CHECK_SIGN);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_DOOR_TIANJIN_JINJING_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_GLASS_TIANJIN_JINJING_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.PSD_GLASS_END_TIANJIN_JINJING_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_DOOR_TIANJIN_JINJING_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_GLASS_TIANJIN_JINJING_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.APG_GLASS_END_TIANJIN_JINJING_BLOCK);
        RegistryClient.registerRenderShape(RenderType.cutout(), BlockList.STATION_SIGN_BMT);

        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_SIGN_1, RenderStationNameSign::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_SIGN_2, RenderStationNameSign::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.TIME_DISPLAY, RenderTimeDisplay::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.TIME_DISPLAY_EVEN, RenderTimeDisplay::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.SERVICE_CORRIDOR_SIGN, RenderServiceCorridorSign::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.ROADBLOCK_SIGN, RenderRoadblockSign::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_4, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_6, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_8, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_10, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_2, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_3, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_4, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_5, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_6, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_7, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_8, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_9, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_BIG_10, RenderRailwaySignWall::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_3_ODD, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_4_ODD, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_5_ODD, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_6_ODD, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_7_ODD, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_2_EVEN, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_3_EVEN, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_4_EVEN, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_5_EVEN, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_6_EVEN, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_7_EVEN, RenderRailwaySignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_DOUBLE_4, RenderRailwaySignWallDouble::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_DOUBLE_6, RenderRailwaySignWallDouble::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_DOUBLE_8, RenderRailwaySignWallDouble::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_WALL_DOUBLE_10, RenderRailwaySignWallDouble::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_ENTRANCE_TIANJIN, RenderStationNameEntranceTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_ENTRANCE_TIANJIN_PINYIN, RenderStationNameEntranceTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_ENTRANCE_TIANJIN_BMT, RenderStationNameEntranceTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_ENTRANCE_TIANJIN_BMT_PINYIN, RenderStationNameEntranceTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_ENTRANCE_TIANJIN_JINJING, RenderStationNameEntranceTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_ENTRANCE_TIANJIN_JINJING_PINYIN, RenderStationNameEntranceTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PSD_TOP_TIANJIN, RenderPSDTopTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PSD_DOOR_TIANJIN, RenderPSDDoorTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_WALL_LEGACY, RenderStationNameWallLegacy::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_PLATE, RenderStationNamePlate::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_2_ODD, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_3_ODD, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_4_ODD, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_5_ODD, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_6_ODD, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_7_ODD, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_2_EVEN, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_3_EVEN, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_4_EVEN, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_5_EVEN, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_6_EVEN, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.RAILWAY_SIGN_TIANJIN_BMT_7_EVEN, RenderRailwaySignTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_DOOR_TIANJIN, RenderAPGDoorTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_DOOR_TIANJIN_BMT, RenderAPGDoorTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_GLASS_TIANJIN_BMT, RenderAPGGlassTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PSD_TOP_TIANJIN_BMT, RenderPSDTopTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PSD_DOOR_TIANJIN_BMT, RenderPSDDoorTianjinBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_DOOR_TIANJIN_TRT, RenderAPGDoorTianjinTRT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_GLASS_TIANJIN_TRT, RenderAPGGlassTianjinTRT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.SECURITY_CHECK_SIGN, RenderSecurityCheckSign::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAVIGATOR_3, RenderStationNavigator::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAVIGATOR_4, RenderStationNavigator::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAVIGATOR_5, RenderStationNavigator::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_PROJECTOR, RenderStationNameProjector::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PSD_TOP_TIANJIN_JINJING, RenderPSDTopTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PSD_DOOR_TIANJIN_JINJING, RenderPSDDoorTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_DOOR_TIANJIN_JINJING, RenderAPGDoorTianjinJinjing::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_GLASS_TIANJIN_JINJING, RenderAPGGlassTianjinJinjing::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.ROUTE_MAP_BMT, RenderRouteMapBMT::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.STATION_NAME_SIGN_TIANJIN, RenderStationNameSignTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PIDS_TIANJIN, dispatcher -> new RenderPIDSTianjin<>(dispatcher, 2.5F, 30, true, 1));
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PIDS_TIANJIN_SINGLE, dispatcher -> new RenderPIDSTianjin<>(dispatcher, 2.5F, 30, false, 1));
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_DOOR_SINGLE_LEFT, RenderAPGDoorTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.APG_DOOR_SINGLE_RIGHT, RenderAPGDoorTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PSD_DOOR_SINGLE_LEFT, RenderPSDDoorTianjin::new);
        RegistryClient.registerBlockEntityRenderer(BlockEntityTypes.PSD_DOOR_SINGLE_RIGHT, RenderPSDDoorTianjin::new);

        RegistryClient.registerEntityRenderer(EntityTypes.SEAT, RenderSeat::new);

        RegistryClient.registerBlockStationColor(BlockList.STATION_COLOR_CEILING, BlockList.STATION_COLOR_CEILING_LIGHT, BlockList.STATION_COLOR_CEILING_NO_LIGHT, BlockList.STATION_COLOR_CEILING_NOT_LIT);
        RegistryClient.registerBlockStationColor(BlockList.STATION_NAME_SIGN_1);
        RegistryClient.registerBlockCustomColor(BlockList.CUSTOM_COLOR_CONCRETE, BlockList.CUSTOM_COLOR_CONCRETE_SLAB, BlockList.CUSTOM_COLOR_CONCRETE_STAIRS);
        RegistryClient.registerBlockCustomColor(BlockList.METAL_POLE_BMT);
        RegistryClient.registerBlockCustomColor(BlockList.CUSTOM_COLOR_MOSAIC_TILE, BlockList.CUSTOM_COLOR_MOSAIC_TILE_SLAB, BlockList.CUSTOM_COLOR_MOSAIC_TILE_STAIRS);
        RegistryClient.registerItemCustomColor(0xfff100, BlockList.METAL_POLE_BMT, "metal_pole_bmt");

        BlockSmokeAlarm.BlockEntity.updateSoundSource = SMOKE_ALARM_SOUND_INSTANCE::setPos;

        RegistryClient.REGISTRY_CLIENT.init();

        ConfigClient.refreshProperties();
    }
}
